### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by chenxiaolong**
For whatever reason, when building caddy 2.6.3 with this plugin via xcaddy, the golang compiler (both 1.19.5 and 1.20) locks up and hangs forever during the `go get -d -v` phase. Updating the dependencies to their latest versions seems to resolve that issue.

### CODE REVIEW

**Review by mholt — APPROVED** [review]
I've seen this before on our build server (not necessarily with this plugin, though) -- I suspect it's a bug in `go get` but the hang can sometimes last for days. :grimacing: Anyway, thanks for the patch!

**Comment by chenxiaolong** [comment]
That was quick, thank you!

> I suspect it's a bug in `go get` but the hang can sometimes last for days.

Wow, and I thought I was patient waiting just two hours before killing the build :smile:

**Comment by tokred** [comment]
For your awareness, my `xcaddy build --with github.com/caddy-dns/rfc2136` still hangs at `[INFO] exec (timeout=0s): /usr/bin/go get -d -v`, even after this commit. Building caddy v2.6.3 without the plugin works just fine. I am on `go1.19.5 linux/amd64`.

Regards

**Comment by mholt** [comment]
It's because the commit needs to be tagged. You can do `--with github.com/caddy-dns/rfc2136@master` to get the latest commit though, and that might work.

**Pull request merged**
